### ISSUE TITLE
assigning the clock in pin planner

### ISSUE THREAD

**Issue by Baungarten-CINVESTAV** [lnis-uofu/OpenFPGA#1096]
Hi every one,

My question is related to the pin planner, at this point i created the ".xml", ".csv", and ".pcf" files in order to use the "pcf2place" command. it works well, i generated my bitstream to configure the FPGA with the specific I/O ports.

MY question is, how can i choose the clk port? or how OpenFPGA identify the clk port to be routed to the global clk?

**Comment by zliu1Charlotte** [comment]
do you need to fix IO pins or you wish to fix clbs?

**Comment by tangxifan** [comment]
@Baungarten-CINVESTAV @zliu1Charlotte Regarding clock, please give a try to the repack design constraint file, if you are considering a multi-clock FPGA fabric.
