### ISSUE TITLE
scan chain configuration mode

### ISSUE THREAD

**Issue by narutozxp** [lnis-uofu/OpenFPGA#1154]
if we use scan chain configuration mode, the vcs simulaiton will be pushed and never will continue. is it due to the combination loop during the config period? 
is there any other way to solve the problems besides using the fame-based configuration mode? thanks!

**Comment by tangxifan** [comment]
Hello, I have not seen such problem when using VCS. See if you do need a config_enable signal to avoid combinational loops.
See the exampe: https://openfpga.readthedocs.io/en/master/manual/arch_lang/circuit_model_examples/#configuration-chain-flip-flop-with-configure-enable-signals
