### ISSUE TITLE
Fail with benchmarks using output DFF assigned 1 when reset active

### ISSUE THREAD

**Issue by anhdv2000** [lnis-uofu/OpenFPGA#1197]
I have a benchmark

module dff01 (
  input clk,    // Clock
  input reset_n,
  input  in,
  output reg  out
  
);
  always @(posedge clk or negedge reset_n) begin 
    if(~reset_n) begin
      out <= 1;
    end else begin
      out <= in;
    end
  end
endmodule : dff01
i run with test tasks/basic_tests/k4_series/k4n4_fracff. But vpp fail output Q_fpga isn't assgined 1 when reset active

**Comment by anhdv2000** [comment]
I have a benchmark
```
module dff01 (
  input clk,    // Clock
  input reset_n,
  input  in,
  output reg  out
  
);
  always @(posedge clk or negedge reset_n) begin 
    if(~reset_n) begin
      out <= 1;
    end else begin
      out <= in;
    end
  end
endmodule : dff01
```
i run with test **tasks/basic_tests/k4_series/k4n4_fracff**. But vpp fail output Q_fpga isn't assgined 1 when reset active

**Comment by tangxifan** [comment]
My suggestion is to create specific FF models where you want active-low set.

**Comment by anhdv2000** [comment]
@tangxifan If I understand correctly, for each benchmark we run, we need to define the appropriate flip-flop in the openfpga.xml file using the following line: <pb_type name="clb.fle[physical].fabric.ff" circuit_model_name="MULTI_MODE_DFFRQ" mode_bits="0"/>.
If that's the case, for benchmarks that contain multiple types of flip-flops, we would also need a configurable flip-flop model that can operate like all the different types of flip-flops, depending on the configuration.
