### ISSUE TITLE
No see "output_load" parameter in k6_frac_N10_adder_Chain_40nm_openfpga.xml

### ISSUE THREAD

**Issue by Nguyenthehuy1** [lnis-uofu/OpenFPGA#1221]
Hello everyone,

I want to find  “output_load” parameter in "k6_frac_N10_adder_Chain_40nm_openfpga.xml" file, but in this file, i only see: 

" <delay_matrix type="rise" in_port="A B" out_port="Z">
        10e-12 8e-12
      </delay_matrix>
       <delay_matrix type="fall" in_port="A B" out_port="Z">
       10e-12 7e-12
     </delay_matrix>"

Above values is propagation time (rise, fall time) but i cannot see “output_load” parameter?

Thank you everyone

**Comment by tangxifan** [comment]
@Nguyenthehuy1 Please do not worry about the output loads. You do not need to accurately annotate the timing here. It is just used for convergence in HDL simulations.
