### ISSUE TITLE
Bug in bintoi_charvec() function

### ISSUE THREAD

**Issue by chungshien** [lnis-uofu/OpenFPGA#1248]
> In ql_memory_bank with flatten BL/WL configuration protocol, we will need to

1. set the BL address - https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga/src/fpga_bitstream/fabric_bitstream.cpp#L192

    BL is basically a string (more accurately vector of char), which the string could contain 'x', '0' or '1'. In this particular use case, normally  BL contains a series don't care bit 'x' and only one '1' bit. Example: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1xxxxxxxxxxxxxxxxxxxxxxxxxxx

2. When we set the BL, we will convert the string into a vector of uint64_t. https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga/src/fpga_bitstream/fabric_bitstream.cpp#L181-L189

    The function will break a long string (hundred of characters) of BL into multiple of 64 chars (or less), each 64 chars will be converted into two uint64_t: one to represent data, one represent dont-care-mask. 

3. To convert the chars chunk into uint64_t, we will eventually call https://github.com/lnis-uofu/OpenFPGA/blob/master/libs/libopenfpgautil/src/openfpga_decode.cpp#L172-L182

    Per my testing, this function does not perform the conversion correctly. For example if we have 64 chars of '1' (for mask we convert 'x' to '1' and the rest to '0'), "1111111111111111111111111111111111111111111111111111111111111111", the expectation of result would be 0xFFFFFFFFFFFFFFFF, but I found that the result is 0. 

   Refer below simple example. 

**P/S: If this is confirmed a bug and we need to fix this. then there are more bugs as well in openfpga_decode.cpp need to be fixed**

> **Which part of OpenFPGA is buggy**

- [x] FPGA-Bitstream

> **To Reproduce**
1. See this simple example code

![image](https://github.com/lnis-uofu/OpenFPGA/assets/124318336/02b730ba-4b3b-4217-83a7-fbd97671ca15)

2. ret0  (line 9) is similar to OpenFPGA implementation. ret1 (line 10) is my workaround where I cast the pow() result to size_t first before addition. 

3. See the printf result. The ret0 result start to becoming problem at i=53, and eventually 64 characters of '1' will become 0 instead of expected result (0xFFFFFFFFFFFFFFFF)

**P/S: I really prefer bit manipulation in bitstream generation instead of mathematic operation for example using pow() function. Maybe compiler might optimize it to become faster/compact since it is power of 2, but to me does not seems to be efficient way of writing code especially involving bitstream**

![image](https://github.com/lnis-uofu/OpenFPGA/assets/124318336/9a981e37-eea8-434c-91ad-46c6de95601b)

**P/S: Same code had been tested on WLS Ubuntu, MSVC 17.3.6 x86_amd64 and gcc 8.3.0 x86_64-w64-mingw32 by two other colleagues - all having same problem**

> **Enviornment (please complete the following information):**

>  - OS: 

- [x] Ubuntu 22.04.2 LTS

>  - Compiler:

- [x] gcc-11

> - Version:

**Comment by alaindargelas** [comment]
@chungshien, please submit a PR with the fix. @tangxifan will review.

**Comment by chungshien** [comment]
Created a PR - https://github.com/lnis-uofu/OpenFPGA/pull/1252

**Comment by chungshien** [comment]
PR is in. Close issue.
