### ISSUE TITLE
Support QL Memory Bank Protocol for Tile-Based Netlists

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#1286]
**Describe the solution you'd like**
Is it possible to tile fabric generation with ql_memory_bank protocols? Scan_chain has some negative sides in aspect of physical design. I would like to use advantages of tile based fabrics and ql_memory_bank protocols together.

**Comment by tangxifan** [comment]
@msaideroglu Currently, we only support CCFF chains as we already see several successfully FPGA chips based on this technology. The QL memory bank will be supported. It is planned in 2023 Q4 as now.

**Comment by msaideroglu** [comment]
Thanks.
