### ISSUE TITLE
Undriven nets called undriven_sram_inv 

### ISSUE THREAD

**Issue by WazaAbdulkadir** [lnis-uofu/OpenFPGA#1346]
Hello,

After generating the FPGA fabric, I noticed that there are undriven nets with the suffix **undriven_sram_inv** in the **logical_tile_clb_mode_clb** and in two other clb netlist as well as in some corner **SB** and **CB**.

I ran the flow for layouts of different sizes and observed that these nets occur in the same positions in the FPGA netlist.

Below are the CB and SB netlist files that include these undriven signals:
 
	cbx_1__0, cbx_1__1, cbx_1__last,
	cby_0__1, cby_1__1, cby_last__1

	sb_0__0, sb_0__1, sb_0__last,sb_1__0,
	sb_1__1, sb_1__last, sb_last__0,sb_last__1,
	sb_last_last

**Note**: last means the biggest row or column number. 

When I check this issue in [SOFA](https://github.com/search?q=repo%3Alnis-uofu%2FSOFA+path%3A%2F%5ESOFA_A%5C%2FFPGA88_SOFA_A%5C%2FFPGA88_SOFA_A_verilog%5C%2FSRCOriginal%5C%2F%2F+undriven&type=code) repository I saw this is valid for them also.

When I follow one of this signals inside of logical_tile_clb_mode_clb.v: 

![image](https://github.com/lnis-uofu/OpenFPGA/assets/47847116/80c37431-3e70-4999-8e84-b28142b7b27b)

![image](https://github.com/lnis-uofu/OpenFPGA/assets/47847116/837f5de7-70b8-4241-890f-d2c90c354aa7)

It is not connected to anywhere as the signal name indicates. 

**How can we remove these undriven signals, or is it necessary to do so?**

Thanks in advance.

**Comment by tangxifan** [comment]
@WazaAbdulkadir The sram_inv port is required when programmable resources consist of transmission gates. If your routing mutlipexers, LUTs, etc, are built with CMOS gates, then you do not need the ``sram_inv`` port. They are dangling. This is expected. If you want to remove them, I suggest to run synthesis.
