### ISSUE TITLE
Why square like fpga layout is common?

### ISSUE THREAD

**Issue by WazaAbdulkadir** [lnis-uofu/OpenFPGA#1395]
When I examine VPR architectures in this repository, I notice that all FPGA layouts are described as square.

What is the reason behind this? I haven't come across any FPGA defined as 6x10; instead, they are described as 2x2, 4x4, 8x8 etc. device layouts.

Is there any design trade-off, such as whether a more square FPGA architecture perform better?

Thanks in advance.

**Comment by tangxifan** [comment]
@WazaAbdulkadir You can find many examples in OpenFPGA showing the support beyond square shapes:

- Rectangle shape: https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_hetero_fabric_tile/config

- L shape: https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/tasks/basic_tests/group_config_block/group_config_block_homo_Lshape_full_testbench/config

Please note that we have silicon proof for rectangle shape already.
