### ISSUE TITLE
Usage of QN and Reset in CC-FFs

### ISSUE THREAD

**Issue by WazaAbdulkadir** [lnis-uofu/OpenFPGA#1403]
In [circuit model examples](https://openfpga.readthedocs.io/en/master/manual/arch_lang/circuit_model_examples/ ) different configuration chain FF examples are given. I have two question about CC-FFs.

1- In all of them inverted data output exist. Could CC-FF has only D,Q and CLK ports without QN port?

2- There are no examples of CC-FF with reset capability. Since initial state of the CC-FF is not important since we will reprogram after power-up, using reset might be non-functional. What are the advantages and disadvantages of using CC-FF with reset capability?

**Comment by tangxifan** [comment]
@WazaAbdulkadir We have provided some representative examples in the documentation. Sorry that we have missed the example with reset, which is actually very common.

1 - If you build a FPGA using only standard cells, you do not need a QN. However, currently I cannot remove the restrictions here in OpenFPGA (will be done later I believe). If you want to go over it, I suggest you to run synthesis on netlists in a flatten way, it can wipe out these dangling ports.

2-  We have provided fruitful examples in the regression tests

- https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_reset/config

- https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_resetb/config

- https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_set/config

- https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain_use_set_reset/config

If you are using reset, you may benefit from some fast configuration techniques 

https://openfpga.readthedocs.io/en/master/manual/openfpga_shell/openfpga_commands/fpga_bitstream_commands/#cmdoption-fast_configuration

Also, if you want a clean start (avoid any combinational loop in datapath), you may need a reset.

2-
