### ISSUE TITLE
How can I open openfpga shell ?

### ISSUE THREAD

**Issue by august-35** [lnis-uofu/OpenFPGA#1423]
Hello, I want to try openfpga shell. I've tried the method mentioned at https://github.com/lnis-uofu/OpenFPGA/issues/75#issuecomment-670038931 , but I find there isn't any excutable file under the path /OpenFPGA/openfpga. So with the command /OpenFPGA/openfpga/ ./openfpga -i I couldn't open the shell.
Could you help me?
Thank you !

**Comment by tangxifan** [comment]
Hello @august-35 , we have standardized the repo organization especially for the build binaries. Now all the binaries can be found  under the ``OpenFPGA/build/``. For example, the openfpga shell is under ``OpenFPGA/build/openfpga/openfpga``

**Comment by august-35** [comment]
I've made it, thank you @tangxifan
