### ISSUE TITLE
Bitstream WL incremental/decremental option is broken 

### ISSUE THREAD

**Issue by chungshien** [lnis-uofu/OpenFPGA#1466]
> **Describe the bug**
> A clear and concise description of what the bug is.

The bitstream WL sequence (can be WL incremental or decremental control via the option) is broken because of commit of https://github.com/lnis-uofu/OpenFPGA/commit/1e8bf1ceceefdaf5c5a93339e82658656a5b659e#diff-039f23a060209f5dafc8ce53956898ff6a954849c7cd96df3b71b85cd7735561L132-L137

**Comment by chungshien** [comment]
I will fix this

@alain-rs
@alaindargelas

**Comment by alaindargelas** [comment]
@chungshien , also maybe a test was missing, so that commit broke the functionality without any apparent failure.
Please add explicit test(s).
