### ISSUE TITLE
New Tileable Layout Structure Request

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#1505]
**Describe the solution you'd like**
The picture below shows an alternative tileable layout structure. Here new tiles seems to be more area-efficient and grid_io's can be repetitively put in floorplan, so that I seperately put grid_io's in fpga_top. I can restructure generated netlist manually, but it gets difficult when the layout size increases. Does suggested way seem reasonable? If yes, would OpenFPGA team consider to adapt this type of tileable netlist generation? Thanks.

![new_tile_structure](https://github.com/lnis-uofu/OpenFPGA/assets/107807649/cb80af77-1fdf-4440-9820-d501a359c835)

**Comment by tangxifan** [comment]
@msaideroglu This makes sense to me. It may lead to some QoR improvements from a physical design perspective. However, the exact QoR improvement is not clear to me. The earliest timeslot we can land this feature is 2024Q3

**Comment by msaideroglu** [comment]
Thanks.
