### ISSUE TITLE
Question about BRAM preload data content

### ISSUE THREAD

**Issue by chungshien** [lnis-uofu/OpenFPGA#1507]
Hi Xifan,

I would like to understand how BRAM preload data content is being generated. Hope you can help me to understand that

For example: 

1. In the project RTL, we will initialize the BRAM with random content from file mem1.mem

![image](https://github.com/lnis-uofu/OpenFPGA/assets/124318336/1a6cf67e-ebfb-4015-9497-033383743737)

2. In the systhesis eblif file, I could see that the content is initialized as part of "param INIT_i"

![image](https://github.com/lnis-uofu/OpenFPGA/assets/124318336/56de2cee-9861-4568-bbb4-baaad1ec9a4b)

Will this BRAM Preload data content being generated as part of bitstream? Do we have BRAM bitstream like what happened in fabric (for example fabric will generate fabric_bitstream.bit)? 

Thanks

**Comment by chungshien** [comment]
@alaindargelas

**Comment by alaindargelas** [comment]
@tangxifan we can see the memory content being preserved by VPR and make it into the post-route netlist, but we cannot find it in the bitstream.

**Comment by tangxifan** [comment]
@alaindargelas @chungshien 

There are multiple ways to implement BRAM preloading.
In your way, you may refer to the bitstream setting file:

https://openfpga.readthedocs.io/en/master/manual/file_formats/bitstream_setting/

where you can extract information from eBLIF file and use it in your bitstream.

**Comment by chungshien** [comment]
Closing this issue as https://github.com/lnis-uofu/OpenFPGA/pull/1566 had been merged.
