### ISSUE TITLE
TSMC lib?

### ISSUE THREAD

**Issue by zliu1Charlotte** [lnis-uofu/OpenFPGA#1510]
Hello, can I use TSMC library on OPENFPGA?
Thanks!

**Comment by tangxifan** [comment]
Sure. You can. Please check the OpenFPGA architecture description language: 

- verilog_netlist="<string>" See details at https://openfpga.readthedocs.io/en/master/manual/arch_lang/circuit_library/#circuit-model

Also you may check how the Skywater library is used on SOFA projects:

https://github.com/lnis-uofu/SOFA/blob/abea1a8aa0a5922aecd5ea3a80d64c6799b46a51/ARCH/openfpga_arch_template/k4_N8_reset_softadder_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml#L34

**Comment by zliu1Charlotte** [comment]
thanks!
