### ISSUE TITLE
How to simulate a large file?

### ISSUE THREAD

**Issue by ducminhnguyen123** [lnis-uofu/OpenFPGA#1520]
@tangxifan my file rtl input of OpenFPGA is a large file which are up to 200000 LUTs and it generate the file: test_top_formal_verification.v. I simulate test_top_formal_verification.v by vcs and questasim tool and because the size of  test_top_formal_verification.v is extremely large, the simulation tool can not simulate (I simulate test_top_formal_verification.v by vcs tool, it took my server up to 160 GB ram). So, with the large design, how do you resimulate to verify the result of OpenFPGA and how long does it take to simulate? how many bytes ram resource does it occupy?

**Comment by tangxifan** [comment]
@ducminhnguyen123 It is difficult to estimate as different HDL simulators behave differently on peak memory usage and runtime. I have not tried 2,000,000 LUT on HDL simulation. My experience is that VCS may take 5G for a 6k-LUT device. So you may see the limited on peak memory usage.
