### ISSUE TITLE
Adopt yosys-symbiflow-plugins for SDC support?

### ISSUE THREAD

**Issue by mithro** [lnis-uofu/OpenFPGA#153]
You might want to consider adopting the usage of the SymbiFlow Yosys Plugins @ https://github.com/SymbiFlow/yosys-symbiflow-plugins to improve your SDC support (and future timing driven synthesis). This works by importing the SDC into Yosys cells and then writing out a modified SDC at the end. This means if Yosys changes module names or optimizes out your modules you still end up with a valid SDC file you can pass to VPR.

**Comment by tangxifan** [comment]
@mithro I think it is a good idea. Is this effort will be merged to yosys master ? We are now adding yosys as a submodule (see pull request #152 ) and it will be very easy to integrate the latest Yosys. 

Otherwise,  I will find a way to integrate this feature.

**Comment by mithro** [comment]
It's an external plugin for Yosys, so it should work with any new Yosys version.

**Comment by tangxifan** [comment]
Bring here the note from #152 :
A follow-up pull request is needed which consider the benchmark [https://github.com/smunaut/iua](https://github.com/smunaut/iua) as a test. That needs SDC to specify the minimum clock requirements to meet USB 2.0 speed.

**Comment by tangxifan** [comment]
https://github.com/SymbiFlow/yosys-symbiflow-plugins is now a submodule of OpenFPGA.
Dependabot has been set up to auto tracking latest updates.

So I close this issue. If you have any question, feel free to propose.
