### ISSUE TITLE
Document seems not correct

### ISSUE THREAD

**Issue by narutozxp** [lnis-uofu/OpenFPGA#1539]
@tangxifan 
In  [online document](https://openfpga.readthedocs.io/en/master/manual/arch_lang/addon_vpr_syntax/), I have seen that layout has an attribution of `concat_wire`. However, the wire connecting doesn't have any difference whether `concat_wire` is disabled or not(the two pictures seem the same). Besides, the arrangement of `Starting routing tracks` and `Ending routing tracks` is different from the paper, "A Study on Switch Block Patterns for Tileable FPGA Routing Architectures", which described a tileable routing architecture.
I don't know which routing architecture is consistent with the current version of OpenFPGA.

**Comment by tangxifan** [comment]
@narutozxp You are right. It has been corrected.
