### ISSUE TITLE
Global ports are connected to GPIOs

### ISSUE THREAD

**Issue by AhmadHouraniah** [lnis-uofu/OpenFPGA#1553]
Hello,
I am using global clock and reset pins in my architecture, however, OpenFPGA is still using GPIOs for these pins (they are connected to the global pins as well as GPIOs). 
The GPIO reset and clock pins are not used in the FPGA, so disconnecting them in the testbench does not cause issues and the simulation still passes.

Is there a way to avoid connecting global pins to GPIOs as it is currently unnecessarily utilizing the ports?

Thanks!

**Comment by tangxifan** [comment]
@AhmadHouraniah Currently, I have no solution on this. It is vpr which has to connect the clock net to a GPIO. The global clock and reset pins are modelled in OpenFPGA but not in VPR. That is why VPR has not visibility on these pins.
