### ISSUE TITLE
Is random fabric key generation the only method for secure user's FPGA IP design? 

### ISSUE THREAD

**Issue by WazaAbdulkadir** [lnis-uofu/OpenFPGA#1563]
There are several methods available to secure FPGA IP designs for end-users. These include single-key encryption, where the bitstream is encrypted using a single key and decrypted at the FPGA/SoC side using the same key, as well as red/black encryption, where both the bitstream and the fabric key are encrypted.

Single key encryption: 

<img src="https://github.com/lnis-uofu/OpenFPGA/assets/47847116/11cfba9e-a987-4bfa-bcf5-d4b6cc7734d0" width=60% height=60%>

Image from the article: https://dl.acm.org/doi/10.1145/2593069.2602555  

Red/Black Encryption: 

<img src="https://github.com/lnis-uofu/OpenFPGA/assets/47847116/6eb4e347-dcda-453d-8e49-1329a56d7ec1" width=60% height=60%>

Image from the article: https://cgi.luddy.indiana.edu/~lukefahr/papers/duncan2019fpga.pdf  

As far as I understand, OpenFPGA provides fabric key generation for FPGA design security, which involves just shifting randomly the order of bitstream loading to the configurable memory (there is no encryption algorithm utilized like DES or AES.) blocks on the FPGA fabric.

I generated bitstreams both with and without using '--generate_random_fabric_key', and then compared the resulting bitstreams. It was just mixing bitstream. 
 
![image](https://github.com/lnis-uofu/OpenFPGA/assets/47847116/f794525b-00b1-4662-b5c0-9ca4dd38aa8a)

Is random fabric key generation which just mixes tile sequences in configuration bitstream only method for securing FPGA IP designs in OpenFPGA?

**Comment by tangxifan** [comment]
@WazaAbdulkadir When I design the fabric key, the motivation is provide users full customization on the configuration circuits. In my experience, it is typically generated by an external script or even hand-crafted.
