### ISSUE TITLE
questions about clock_network

### ISSUE THREAD

**Issue by Chris202305** [lnis-uofu/OpenFPGA#1571]
May I ask what the meanings of INC_DIRECTION and DEC_DIRECTION after this DIRECTION are? If I want to change it to a spine_lvl0 from top to bottom, what should the "direction= " in these horizontal rib definitions be changed to? This information is not explained in the documentation.
![1708242541726](https://github.com/lnis-uofu/OpenFPGA/assets/142561908/9e508395-0186-4ba3-a3ad-6c213ce07814)

**Comment by tangxifan** [comment]
@Chris202305 INC_Direction means 
- horizontal tracks that span from left to right
- vertical tracks that span from bottom to top

DEC_DIRECTION means
- horizontal tracks that span from right to left
- vertical tracks that span from top to bottom

**Please be aware the programmable clock network is still under development, bugs and errors may easily be hit. I do not have bandwidth to work on this part in a short term.**
