### ISSUE TITLE
Issue when running 3 ram 

### ISSUE THREAD

**Issue by ducminhnguyen123** [lnis-uofu/OpenFPGA#1572]
Dear Tangxifan,

I have encoutered an issue when running 3 ram in openfpga. Some bits of input signals of 3 ram are X as the picture below
![10](https://github.com/lnis-uofu/OpenFPGA/assets/96974240/ee92c11c-e513-464c-a81f-cd2fd6da8bda)
But when I run each ram, it worked perfectly like the picture below
![11](https://github.com/lnis-uofu/OpenFPGA/assets/96974240/227d9319-420b-47e2-add1-caddefc9f8b7)
I thịnk maybe I place the pins of ram incorrectly in openfpga (the picture below):
![12](https://github.com/lnis-uofu/OpenFPGA/assets/96974240/73642e9c-9562-4c97-8469-efbba3261530)
Can you give me the solutions for this issue, pls!
This is my running file (include vpr architecture, benmark, ...).
[iwls2005.tar.gz](https://github.com/lnis-uofu/OpenFPGA/files/14340570/iwls2005.tar.gz)
This is the testbench:
[dual_port_ram_1k_formal_random_top_tb.v.tar.gz](https://github.com/lnis-uofu/OpenFPGA/files/14326674/dual_port_ram_1k_formal_random_top_tb.v.tar.gz)
the file links in task.conf and k6_frac_N10_adder_chain_dpram8K_dsp36_fracff_40nm_openfpga.xml is the relative link and are needed to write.

Best regard,
Duc

---------------------------------------------------------------------------------------------------------------------------------------------------------------------
P/s: @tangxifan

**Comment by tangxifan** [comment]
@ducminhnguyen123 I believe it is the same issue as https://github.com/lnis-uofu/OpenFPGA/issues/1501#issuecomment-2091675577

See my answer there.
