### ISSUE TITLE
Documentation - dead links

### ISSUE THREAD

**Issue by grantsmith1969** [lnis-uofu/OpenFPGA#161]
**Describe the bug**
https://openfpga.readthedocs.io/en/master/tutorials/tools.html etc are dead.

**To Reproduce**
click on any of the documentation links in the readme
**Expected behavior**
to link to the docs :)

**Comment by tangxifan** [comment]
@grantsmith1969 Thank you for pointing out the out-of-date links. I have proposed a patch and it should address the issue.

**Comment by tangxifan** [comment]
@grantsmith1969 Just merged the patch to master. You can find the right link to the webpage.
