### ISSUE TITLE
Move OpenFPGA docs to github pages 

### ISSUE THREAD

**Issue by ganeshgore** [lnis-uofu/OpenFPGA#181]
**Is your feature request related to a problem? Please describe.**
Move doc building to gh-pages than readthedocs, because 
1. reduces the dependencies on other services 
2. gh-pages are more customizable

**Describe the solution you'd like**
Create a docker image to build docs on the master branch and deploy on dedicated gh-pages branch

**Describe alternatives you've considered**
Seems feasible to achieve above thing 

**Additional context**
It will be great if we could build docs for push requests as well (if there are any changes) and have it hosted in the same github pages. It will make documentation review much faster.

**Comment by tangxifan** [comment]
Currently, readthedocs is still working well. We can preview the documentation for any pull request: 

![image](https://user-images.githubusercontent.com/11499826/105617134-39bd8300-5d9a-11eb-8188-cb93983e262f.png)

So, I will hold this issue until that readthedocs can no longer fit our needs.

**Comment by mithro** [comment]
I would highly recommend sticking with readthedocs.
