### ISSUE TITLE
Regression tests not run for yosys submodule updates

### ISSUE THREAD

**Issue by tangxifan** [lnis-uofu/OpenFPGA#198]
**Describe the bug**
Regression tests in CI are skipped when there is an update in yosys submodule 

**To Reproduce**
See the screenshot attached. 

**Expected behavior**
Regression tests should be invoked in CI when there is a change in the yosys submodule.
Otherwise, there is no guarantee that OpenFPGA can be functional.

**Screenshots**
![image](https://user-images.githubusercontent.com/11499826/106029589-7c2cdb80-608a-11eb-983e-212b4da7e6ec.png)

**Enviornment (please complete the following information):**
 - OS: CentOs
 - Compiler: gcc
 - Version: latest master

**Comment by tangxifan** [comment]
@ganeshgore I would like to know why it happened and how soon we can address it.

**Comment by ganeshgore** [comment]
I will check this and fix, today
