### ISSUE TITLE
Readline not installed by default on Ubuntu

### ISSUE THREAD

**Issue by apond308** [lnis-uofu/OpenFPGA#211]
When compiling, error comes up saying Readline library not found. Need to add 'libreadline-dev' to dependencies in travis.yaml

1. Clone repository
2. Install dependencies found in travis.yaml
3. 'make all' in top directory
4. Compilation will halt with error message

Just need to add 'libreadline-dev' to dependency list in travis.yaml.

**Comment by yashton** [comment]
travis.yaml is out of date. use the dependencies in .github/workflows/install_dependencies_build.sh

**Comment by apond308** [comment]
Closed, will update the documentation to point to .github/workflows/install_dependencies_build.sh.
