### ISSUE TITLE
External users have errors when building docker image on CI

### ISSUE THREAD

**Issue by tangxifan** [lnis-uofu/OpenFPGA#258]
**Describe the bug**
Current docker image building step in CI requires the contributors to be a collaborator of the project.

**To Reproduce**
1. Check the error messages in the docker image building step in PR #257 and PR #247 

**Expected behavior**
The CI should not be limited to the collaborator of the project

**Screenshots**
The error message 
![image](https://user-images.githubusercontent.com/11499826/109532162-13b09000-7a76-11eb-8548-d8077cceb5e1.png)

**Enviornment (please complete the following information):**
 - OS: ubuntu
 - Compiler gcc
 - Version: latest master

**Comment by ganeshgore** [comment]
@yashton Can you look into this ?
This is the CI run 
https://github.com/lnis-uofu/OpenFPGA/actions/runs/610908414

**Comment by yashton** [comment]
Will do
