### ISSUE TITLE
Dependencies not found

### ISSUE THREAD

**Issue by Fre29** [lnis-uofu/OpenFPGA#315]
Which part of OpenFPGA is buggy:
--- >Documentation

Hi,
I'm trying to install OpenFPGA on my laptop (with Ubuntu 21.04) following all steps mentioned in the tutorial "OpenFPGA tutorial: How to install OpenFPGA?". Unfortunately when it's time to verify if the tool is well compiled, with the command: 

python3 openfpga_flow/scripts/run_fpga_task.py compilation_verification --debug --show_thread_logs

I receive these errors:

![Screenshot1](https://user-images.githubusercontent.com/84871203/119778777-33feb800-bec8-11eb-9905-d19f773efc50.png)

I think the problem is linked with installation of the dependencies as I needed to change some of them. More specifically, when I attempt to install those recommended in this link:

https://github.com/lnis-uofu/OpenFPGA/blob/master/.github/workflows/install_dependencies_build.sh

I get this message:

![Screenshot2](https://user-images.githubusercontent.com/84871203/119778874-4c6ed280-bec8-11eb-8b31-160b18c6b3ec.png)

So I found these alternative possibilities: 

- universal-ctags instead of ctags

- qtbase5-dev instead of qt5-default

Are these solutions wrong?

Enviornment:
- OS: 
Ubuntu 21.04 

- Compiler:
gcc-9 ---> 9.3.0

**Comment by TOM-once** [comment]
Your installation is missing EnvYAML
You need to
python -m pip install EnvYAML
pip install --upgrade EnvYAML

**Comment by tangxifan** [comment]
@Fre29 Please find details in #280 

@TOM-once Thanks for the help! That is the solution.

**Comment by Fre29** [comment]
Thanks, both of you. Now it's working correctly!
