### ISSUE TITLE
Unit of task results

### ISSUE THREAD

**Issue by TOM-once** [lnis-uofu/OpenFPGA#332]
Hi,
When I run Python and complete this process, I get the task results, but I don't know the units of the parameters, such as some large circuit, its units seem to get larger, resulting in small data，such as total_logic_block_area =1
![image](https://user-images.githubusercontent.com/85151493/122506036-18eb1800-d030-11eb-93f3-613205548555.png)

Best regards

**Comment by tangxifan** [comment]
@TOM-once The unit for
- time is second
- critical path delay is second
- area is computed in terms of Minimum Width Transistor Area (MWTA). 

For larger circuit, if turn on auto sizing in VPR, the array size will be increased to fit your design. That is why you see area is increased.
