### ISSUE TITLE
Typo in shell script

### ISSUE THREAD

**Issue by lukefahr** [lnis-uofu/OpenFPGA#333]
https://github.com/lnis-uofu/OpenFPGA/blob/b16de387f92d132ccc0d9b682aab1c64e15e39ea/openfpga_flow/openfpga_shell_scripts/fix_device_route_chan_width_example_script.openfpga#L58

This part: 
--bitstream fabric_bitsream.bit

Should read as follows (not the extra t in fabric_bitstream)
--bitstream fabric_bitstream.bit

**Comment by tangxifan** [comment]
@lukefahr Thanks for pointing this out. Will patch immediately.
