### ISSUE TITLE
Minimum Routing Channel Width 

### ISSUE THREAD

**Issue by ishmamiqbal** [lnis-uofu/OpenFPGA#369]
Hello,

When trying to generate a fabric netlist using the example script (in Section 4.1.1 in the OpenFPGA documentation), I am encountering the following error:

```
bash-4.2$ python3 openfpga_flow/scripts/run_fpga_task.py basic_tests/generate_fabric
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task basic_tests/generate_fabric
 INFO (     MainThread) - Created "run008" directory for current task run
 INFO (     MainThread) - Running "vpr_blif" flow
 INFO (     MainThread) - Found 1 Architectures 1 Benchmarks & 1 Script Parameters
 INFO (     MainThread) - Created total 1 jobs
ERROR (00_and2_MIN_ROUTE_CHAN_WIDTH) - Failed to execute openfpga flow - 00_and2_MIN_ROUTE_CHAN_WIDTH
Traceback (most recent call last):
  File "openfpga_flow/scripts/run_fpga_task.py", line 451, in run_single_script
subprocess.CalledProcessError: Command ..........
```

I was reviewing Issue #228 and I understand this might be due to an incorrect minimum routing channel width. But I have set  openfpga_vpr_route_chan_width in task.conf to both 40 and 20, and I am still getting the same error output. How could I solve this issue? Thanks!

**Comment by tangxifan** [comment]
@ishmamiqbal In this case, would you mind share the openfpga_shell.log file or vpr_stdout.log in your local run directory?

**Comment by tangxifan** [comment]
@ishmamiqbal Hope this issue has been fixed. If not, feel free to comment and reopen the issue.

Close it for now.
