### ISSUE TITLE
Compilation in Arm64

### ISSUE THREAD

**Issue by sildipankar** [lnis-uofu/OpenFPGA#370]
Can OpenFPGA be compiled on Arm64 Architecture? Like Yosys supports Arm64 arch

**Comment by tangxifan** [comment]
@sildipankar OpenFPGA is continuously tested in Ubuntu 18.04 and CentOS 7 system. We have not tested on Arm64 arch yet. But this is totally doable. If you see any errors, please feel free to file an issue.

**Comment by tangxifan** [comment]
Close the issue as answered. If you need further help, please comment (reopen this issue) or create a new issue.
Thank you for the interests in OpenFPGA.
