### ISSUE TITLE
VVP Verification fails benchmarks with multi-bit width ports

### ISSUE THREAD

**Issue by apond308** [lnis-uofu/OpenFPGA#386]
When running OpenFPGA with "openfpga_shell_scripts/write_full_testbench_example_script.openfpga", the run fails when it runs vvp_verification.

This happens when the benchmark uses ports that are wider than 1 bit. In the <benchmark_name>_autocheck_top_tb, the busses are flattened, and the benchmark module is instantiated with multiple single bit flattened ports, not the n-width ports, which throws an error.

**Comment by Mistal1999** [comment]
Is there any quick methods to solve this error?

**Comment by tangxifan** [comment]
Close as #360 already reported it.
