### ISSUE TITLE
Promblems about FPGA source occupancy

### ISSUE THREAD

**Issue by Mistal1999** [lnis-uofu/OpenFPGA#388]
Is there any files allow me to check my FPGA source occupancy quickly?

**Comment by tangxifan** [comment]
@Mistal1999 Can  you elaborate your question? I did not get the pain point here.
@ganeshgore Do you have any insights?

**Comment by Mistal1999** [comment]
How many LEs and memory are used in FPGA is very important.  I can quickly check related information in  software like vivado, is there such a file in OpenFPGA?
