### ISSUE TITLE
yosys directory systematically recompiled when compiling OpenFPGA

### ISSUE THREAD

**Issue by xtofalex** [lnis-uofu/OpenFPGA#389]
> **yosys directory is always recompiled**
> Even after running a full package compilation, rerunning make reruns yosys compilation even without any change.

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. clone OpenFPGA repository
> 2. cd OpenFPGA
> 3. make all
> 4. make all 
> 5. See that second make recompiles yosys

> **Expected behavior**
> Second compilation should not recompile anything

> **Version**
  - Current master

**Comment by tangxifan** [comment]
@xtofalex should be addressed in #426. Would you mind update OpenFPGA and give a try? 
If it is working fine, please close this issue.
Otherwise, just let us know and we will follow up

**Comment by xtofalex** [comment]
Working fine. Closing.
Thanks
Christophe
