### ISSUE TITLE
iverilog verification run failed wrong with the adder_4

### ISSUE THREAD

**Issue by Mistal1999** [lnis-uofu/OpenFPGA#390]
[00_adder_4_MIN_ROUTE_CHAN_WIDTH_out.log](https://github.com/lnis-uofu/OpenFPGA/files/7357275/00_adder_4_MIN_ROUTE_CHAN_WIDTH_out.log)
Sorry to bother you again.  As the log said, iverilog verification run failed because 

ERROR - iverilog_verification run failed with returncode 12
ERROR - command iverilog -o compiled_adder_4 ./SRC/adder_4_include_netlists.v -s adder_4_autocheck_top_tb
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``a_0_'' is not a port of REF_DUT.
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``a_1_'' is not a port of REF_DUT.
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``a_2_'' is not a port of REF_DUT.
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``a_3_'' is not a port of REF_DUT.
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``b_0_'' is not a port of REF_DUT.
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``b_1_'' is not a port of REF_DUT.
ERROR - -->>././SRC/adder_4_autocheck_top_tb.v:260: error: port ``b_2_'' is not a port of REF_DUT.

the OpenFPGA has already generate the testbench file.  Same problem on fifo iverilog verification as well. 
I want to know which part  went wrong.

**Comment by tangxifan** [comment]
@Mistal1999 See detailed explanation in https://github.com/lnis-uofu/OpenFPGA/issues/386
