### ISSUE TITLE
Remove the hard requirement on signal activity file in the OpenFPGA vpr_blif flow

### ISSUE THREAD

**Issue by rakeshm75** [lnis-uofu/OpenFPGA#401]
Currently, signal activity file (*.act) is required as a mandatory input for the OpenFPGA vpr_blif flow.

Can we remove the signal activity file requirement to run the OpenFPGA vpr_blif flow.

**Comment by ganeshgore** [comment]
Yeah, we need to see how it affects the flow.
If the simulation setting is provided explicitly I guess you can just provide the dummy `.blif` file.

**Comment by tangxifan** [comment]
@rakeshm75 @tpagarani Once the PR #737 is merged, this limitation should be removed.
