### ISSUE TITLE
QuickLogic test is currently off due to Yosys v0.10 upgrade

### ISSUE THREAD

**Issue by tangxifan** [lnis-uofu/OpenFPGA#405]
> **Describe the bug**
> A clear and concise description of what the bug is.

- [x] OpenFPGA flow

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Clone OpenFPGA repository and checkout commit id: 4e50644
> 2.  QuickLogic tests are disabled because their synthesis recipe is not yet in the Yosys v0.10 release

https://github.com/lnis-uofu/OpenFPGA/blob/4e50644ea866e30ea8dadb67d127a27f8fa6375a/openfpga_flow/regression_test_scripts/quicklogic_reg_test.sh#L11-L21

> **Expected behavior**
> Should enable it soon so that the soft adder support is tested.

> **Enviornment (please complete the following information):**

>  - OS: 

>  - Compiler:

> - Version:

**Comment by tangxifan** [comment]
@tpagarani @coolbreeze413 You may consider to bring the Quicklogic scripts to the upstream and we can bump up the yosys submodule.

**Comment by coolbreeze413** [comment]
Added tests with #420

**Comment by tangxifan** [comment]
@coolbreeze413 Just a reminder. There are still a few quicklogic tests off: counter_5clock_test, sdc_controller_test, lut_adder_test.
When they are all back. We can safely close this issue

**Comment by coolbreeze413** [comment]
@tangxifan I will check about adding those as well

**Comment by tangxifan** [comment]
All done by PR #420 and #421
