### ISSUE TITLE
Functionality to compile only OpenFPGA engine.

### ISSUE THREAD

**Issue by aram-rs** [lnis-uofu/OpenFPGA#411]
**Is your feature request related to a problem? Please describe.**
The feature will reduce compilation time when the user is not interested in yosys build.

**Describe the solution you'd like**
Add `compile_openfpga` target in the Makefile which will execute CMAKE with flags that will disable yosys build.

**Describe alternatives you've considered**
Alternatively a new target can be added to the Makefile which will combine checkout with the build of only OpenFPGA engine.

**Additional context**
Users having custom Synthesis tools will benefit from this future.

**Comment by tangxifan** [comment]
@tpagarani @coolbreeze413 Would you mind modifying our Makefile to support this feature? It will help us in testing different yosys versions from containers. Let me know what you think.

**Comment by tangxifan** [comment]
Close as PR #426 is merged
