### ISSUE TITLE
vvp error "compiled_fifo: unable to open input file"

### ISSUE THREAD

**Issue by Mistal1999** [lnis-uofu/OpenFPGA#417]
Hello! After generating the compiled_fifo manually using iverilog, I begin to use vvp to generate '.vcd' file. But it throws an error called 'compiled_fifo: unable to open input file'，however it could work when I 'vvp compiled_xor2' , I have tried to use command chmod to change the permission of the file. It does not work. How do I solve this problem.
![image](https://user-images.githubusercontent.com/91942648/141664512-dc037b7d-5e63-41cf-b0a4-a8c94dc0b64a.png)

**Comment by Fan1024** [comment]
me too. Do you solve that problem?
