### ISSUE TITLE
 vvp simulation takes too long

### ISSUE THREAD

**Issue by Mistal1999** [lnis-uofu/OpenFPGA#418]
Hello, sorry to disturb. When I use vvp to simulate the compiled_fifo. It will take a long time to finish. I have set the time to ‘20000’. At the same time I tried to simulate the complied_adder_4, and I set the time at ‘20000’  as well. However it's simulation complete much quicker than fifo. How could that happen? It is related to my circuit? Same situiation happens on 4 input multipler as well.

**Comment by tangxifan** [comment]
Based on my experience, iVerilog does not work for large FPGA fabrics (beyond its capability). Please consider to use commercial simulators. See #438
