### ISSUE TITLE
some question about run task

### ISSUE THREAD

**Issue by kangliyu1** [lnis-uofu/OpenFPGA#447]
Hello! I recently used the k6_frac_N10_adder_chain_dpram8K_dsp36_fracff_40nm_openfpga.xml and k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm.xml of the OpenFPGA platform (after I modified the DSP_unit/task/fixed_laygaout_python3/task/fixed_laygaout_python3 command, I used the fixed_laygaout_flow_python3_set_f/pgaout_flow command, as shown in Figure 1) FPGA soft core of BRAM/CLB/IO resources , and related documents such as bitstream that produced the benchmark circuit.

Question 1: When running the existing bench2_top = mac_4 and other examples, the entire process can run through, but when running the code written by myself, the entire process does not work. Some errors and errors appear in the corresponding openfpgashell.log file. Warning, as shown below, I hope some seniors can answer their doubts, thank you very much!

Question 2: According to the description of the k6_frac_N10_adder_chain_dpram8K_dsp36_fracff_40nm_openfpga.xml file, the generated CLB module has 10 6-input LUTs. The resource diagram after the corresponding circuit layout in Vivado is shown in Figure 2, and the corresponding openfpga shell.log The errors shown in the file include those shown in Figure 3. Obviously the result of layout and routing is unreasonable. It actually needs 1553 CLBs (the CLB of the K6N10 structure has 10 6-input LUTs), and the result of layout and routing in Vivado is only It takes less than a thousand LUTs, and I am very confused about this. I hope someone can give me some advice. 
Thank you very much!
fig :1
![image](https://user-images.githubusercontent.com/76480905/146378661-378de454-d15b-4541-b36d-0267599de476.png)

error&warning
```
.......
Finish prepacking.
Using inter-cluster delay: 1.33777e-09
Packing with pin utilization targets: io:1,1 clb:0.8,1 memory:1,1 mult_36:1,1
Packing with high fanout thresholds: io:128 clb:32 memory:128 mult_36:128
Not enough resources expand FPGA size to (62 x 44)
....
Complex block 951: '$abc$191090$memory\mul_res$wrmux[13][35][0]$y$157905[7]' (clb) ..........
Complex block 952: '$abc$191090$memory\mul_res$wrmux[23][35][0]$y$159813[7]' (clb) .........
Failed route at end, repack cluster trying detailed routing at each stage.
Complex block 952: '$abc$191090$memory\mul_res$wrmux[23][35][0]$y$159813[7]' (clb) .........
......
Warning 146: No routing path for connection to sink_rr 7267, retrying with full device bounding box
Cannot route from io[0].inpad[0] (RR node: 1702 type: SOURCE location: (54,0) class: 13 capacity: 1) to clb.clk[0] (RR node: 7267 type: SINK location: (47,1) class: 25 capacity: 1) -- no possible path
Failed to route connection from 'clk' to '$abc$191090$new_n11357_' for net 'clk' (#245)
Routing failed.
# Routing took 17.42 seconds (max_rss 690.8 MiB, delta_rss +56.5 MiB)
Circuit is unroutable with a channel width factor of 300.
VPR failed to implement circuit
The entire flow of VPR took 233.73 seconds (max_rss 690.8 MiB)
....
Warning 5778: Override the previous node '433646' by previous node '433676' for node '179893' with in routing context annotation!
Warning 5779: Override the previous node '179897' by previous node '179893' for node '179845' with in routing context annotation!
Warning 5780: Override the previous node '601958' by previous node '601928' for node '193253' with in routing context annotation!
...
Build fabric module graph
# Build constant generator modules
# Build constant generator modules took 0.00 seconds (max_rss 713.1 MiB, delta_rss +0.0 MiB)
**# Build u/home/kly/OpenFPGA/openfpga/src/repack/repack.cpp:189 rec_find_routed_sink_pb_graph_pins: Assertion 'true == found_actual_sink_pb_pin' failed.**
-6
........
```
fig :2
![image](https://user-images.githubusercontent.com/76480905/146378715-db6d79d8-f068-43c0-a354-7523356ab553.png)

log:3
```
Error 1: 
Type: Other
File: /home/kly/OpenFPGA/vpr/src/pack/pack.cpp
Line: 180
Message: Failed to find device which satisifies resource requirements required: io: 282, clb: 1553, mult_36: 21, memory: 3 (available io: 1312, clb: 1260, mult_36: 35, memory: 105)
Error 2: Command 'vpr' execution has fatal errors
1
```
中文:
您好！我最近在使用OpenFPGA平台的k6_frac_N10_adder_chain_dpram8K_dsp36_fracff_40nm_openfpga.xml与k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm.xml（修改了fixed_layout部分,如图一所示）在使用python3 openfpga_flow/scripts/run_fpga_task.py benchmark_sweep/mac_units指令运行后，产生了一个带有DSP/BRAM/CLB/IO资源(60*42)的FPGA软核，以及产生了benchmark电路的bitstream等相关文件。
问题一：在运行已有的bench2_top = mac_4等例子时整个流程是可以跑通的，但是在运行自己写的代码时整个流程是跑不通的，在相应的openfpgashell.log文件中出现了一些error以及warning，如下所示，希望有前辈可以解答一下疑惑，万分感谢！
问题二：按照k6_frac_N10_adder_chain_dpram8K_dsp36_fracff_40nm_openfpga.xml文件的描述，生成的CLB模块是有10个6输入的LUT，在Vivado中相应的电路布局布线后的资源图如图二所示，而在相应的openfpga shell.log文件中显示的错误包括图三所示的，显然布局布线的结果是不合理的，居然需要1553个CLB(K6N10结构的CLB具有10个6输入的LUT)，而在Vivado中布局布线的结果只需要不到一千个LUT，本人对此感到很困惑，希望有前辈可以指点一下，万分感谢！

**Comment by tangxifan** [comment]
OpenFPGA's synthesis scripts are considered to be general purpose. Therefore, they are well optimized for a specific architecture. As a result, you may see synthesis overhead like this. If you want to improve, you may create your own synthesis scripts like those under https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/misc
