### ISSUE TITLE
some question about pin constraints

### ISSUE THREAD

**Issue by kangliyu1** [lnis-uofu/OpenFPGA#465]
Hello! In the last pin constraint question, you replied that I used the .place file to perform pin constraint on the application circuit. The specific method of your response is shown in Figure 1. I would like to ask you in openfpga Can the integrated VPR change the generated .place file as you said, then skip the packing and placement and re-run VPR? If you need to operate the above steps in an external independent VPR, how can you continue to use the results in the openfpga process after running it?
And I found that the VPR integrated by your openfpga does not support the usage of "vpr --fix_clusters {a.place}", so I would like to ask you again how to implement pin constraints on the application circuit (I hope you can describe more specifically) Thank you very much! ! !
![image](https://user-images.githubusercontent.com/76480905/147639872-395df63b-4586-45c0-9640-afe7d7891da1.png)

**Comment by tangxifan** [comment]
@kangliyu1 In this case, you have to run 
- VPR outside openfpga shell once, where you finish packing and placement.
- Modify .place file 
- Call VPR second time in the openfpga shell, where you redo placement and continue to finish the flow.
