### ISSUE TITLE
TCL shell support in OpenFPGA

### ISSUE THREAD

**Issue by nadeemyaseen-rs** [lnis-uofu/OpenFPGA#516]
Currently OpenFPGA has its own shell and support various command as describe [here](https://openfpga.readthedocs.io/en/master/manual/openfpga_shell/launch_openfpga_shell/). This shell does not support TCL command as most of the EDA tools does. 
As OpenFPGA commands are developed in C++ language so there are many libraries/tools which can be used to expose these commands in TCL shell. One of the such tool is [SWIG](http://www.swig.org/) which can be used to expose the C++ API in high level scripting languages like TCL.

**SWIG working:**  

To expose the c/c++ API in TCL shell, 
* we need to write a interface file. In this interface file we declare the function/class/global variables or if we have a header file which has all the required declarations then we can just simply include it in interface file. 
* This interface file is then passed to SWIG tool which generate the c or c++ wrapper code. 
* This generated wrapper code along with other source code is passed to c/c++ compiler to create non-linked object code. 
* From these created objects code, we need to generate the shared library which is then loaded in TCL shell. 
* Once loaded we can call the declared function/class/global variable or in case of header file what was in header file in TCL shell.

**Example:**

Lets say we have this c++ code:

```
 /* File : example.c */
 
 #include <time.h>
 double My_variable = 3.0;
 
 int fact(int n) {
     if (n <= 1) return 1;
     else return n*fact(n-1);
 }
 
 int my_mod(int x, int y) {
     return (x%y);
 }
 	
 char *get_time()
 {
     time_t ltime;
     time(&ltime);
     return ctime(&ltime);
 }

```   

It's interface file is:

```
 /* example.i */
 %module example
 %{
 /* Put header files here or function declarations like below */
 extern double My_variable;
 extern int fact(int n);
 extern int my_mod(int x, int y);
 extern char *get_time();
 %}
 
 extern double My_variable;
 extern int fact(int n);
 extern int my_mod(int x, int y);
 extern char *get_time();

```

The shared library can be generated using the below command (assuming that you have installed SWIG)

` unix % swig -tcl example.i`
unix % gcc -fpic -c example.c example_wrap.c -I/usr/local/include` 
` unix % gcc -shared example.o example_wrap.o -o example.so`

Start TCL shell, load the shared library and call the functions:

` unix % tclsh`
` % load ./example.so example`
```
 % puts $My_variable
 3.0
```
```
 % fact 5
 120
```
```
 % my_mod 7 3
 1
```
```
 % get_time
 Sun Feb 11 23:01:07 2018
```

The complete SWIG documentation is [here](http://www.swig.org/Doc4.0/SWIG.html#SWIG_nn2)

**SWIG with OpenFPGA:**

In OpenFPGA the compilation and linking of c/c++ code is done using CMake. In OpenFPGA, the most simple is `print_openfpga_version_info` function, if we want to print to the OpenFPGA version information in TCL shell following changes can be done:

1. Create the interface file `openfpga.i` in `openfpga/src/base` directory with following content:

```
/* File : openfpga.i */
%module openfpga

%{
extern void print_openfpga_version_info();
%}

/* Let's just wrap the required function only */
extern void print_openfpga_version_info();   
```
Run the below command to generate wrapper c++ code. (assuming that you have SWIG installed)

`swig -tcl -c++ -cppext cpp openfpga.i`

2. As in the generated wrapper, `tcl.h` is include so add `find_package(TCL)` in CMakeLists.txt to find OS installed TCL package.

3. Add `-fpic` for generating shared library and `-ltcl` to dynamically linked the shared library with `tcl.h`  in CMakeList.txt These flags can be added [here](https://github.com/lnis-uofu/OpenFPGA/blob/92ede44828fe89b6e4d877372e8d58260a21af5c/CMakeLists.txt#L152).
  
4. In `openfpga/CMakeLists.txt` [here](https://github.com/lnis-uofu/OpenFPGA/blob/92ede44828fe89b6e4d877372e8d58260a21af5c/openfpga/CMakeLists.txt#L14), change the keyword `STATIC` to `SHARED`

5. Now run the OpenFPGA build command as usual i.e.
`make all`

6. Once the build completed successfully, go to `openfpga` directory, and run below commands:
     * Start TCL shell
               `tclsh`
     * Load the generated shared library
              `load ./libopenfpga.so openfpga`
     * call the version print function
              `print_openfpga_version_info`

**Comment by tangxifan** [comment]
Close as #915 is being resolved
