### ISSUE TITLE
Building make Error on Centos7 -> Support CentOS 7 in CI

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#562]
I'm getting this error on my centos 7 machine when "make all" command was running. 

My gcc version output is: 
@localhost OpenFPGA]$ gcc --version
gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Error:
[ 78%] Building CXX object vpr/CMakeFiles/libvpr.dir/src/analysis/timing_reports.cpp.o
In file included from /usr/include/tbb/enumerable_thread_specific.h:32,
                 from /usr/include/tbb/combinable.h:32,
                 from /home/synopsys/OpenFPGA/libs/EXTERNAL/libtatum/libtatum/tatum/graph_walkers/ParallelLevelizedWalker.hpp:8,
                 from /home/synopsys/OpenFPGA/libs/EXTERNAL/libtatum/libtatum/tatum/graph_walkers.hpp:9,
                 from /home/synopsys/OpenFPGA/libs/EXTERNAL/libtatum/libtatum/tatum/analyzer_factory.hpp:10,
                 from /home/synopsys/OpenFPGA/vpr/src/timing/timing_info.h:6,
                 from /home/synopsys/OpenFPGA/vpr/src/analysis/timing_reports.cpp:10:
/usr/include/tbb/concurrent_vector.h: In member function ‘tbb::concurrent_vector<T, A>::iterator tbb::concurrent_vector<T, A>::grow_by(tbb::concurrent_vector<T, A>::size_type)’:
/usr/include/tbb/concurrent_vector.h:667:38: error: operands to ?: have different types ‘tbb::internal::concurrent_vector_base_v3::size_type’ {aka ‘long unsigned int’} and ‘tbb::atomic<long unsigned int>’
         return iterator(*this, delta ? internal_grow_by( delta, sizeof(T), &initialize_array, NULL ) : my_early_size);
                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tbb/concurrent_vector.h:667:38: note:   and each type can be converted to the other
/usr/include/tbb/concurrent_vector.h: In member function ‘tbb::concurrent_vector<T, A>::iterator tbb::concurrent_vector<T, A>::grow_by(tbb::concurrent_vector<T, A>::size_type, tbb::concurrent_vector<T, A>::const_reference)’:
/usr/include/tbb/concurrent_vector.h:680:38: error: operands to ?: have different types ‘tbb::internal::concurrent_vector_base_v3::size_type’ {aka ‘long unsigned int’} and ‘tbb::atomic<long unsigned int>’
         return iterator(*this, delta ? internal_grow_by( delta, sizeof(T), &initialize_array_by, static_cast<const void*>(&t) ) : my_early_size);
                                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/tbb/concurrent_vector.h:680:38: note:   and each type can be converted to the other
make[3]: *** [vpr/CMakeFiles/libvpr.dir/src/analysis/timing_reports.cpp.o] Error 1
make[3]: Leaving directory `/home/synopsys/OpenFPGA/build'
make[2]: *** [vpr/CMakeFiles/libvpr.dir/all] Error 2
make[2]: Leaving directory `/home/synopsys/OpenFPGA/build'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/synopsys/OpenFPGA/build'
make: *** [all] Error 2

**Comment by tangxifan** [comment]
Base on what I see, if CentOS8 is used, we cannot guarantee compilation compatibility now.
Currently, OpenFPGA's compilation compatibility is continuously checked on the following settings

 
![image](https://user-images.githubusercontent.com/11499826/156233428-b2913c7c-2afb-4ac3-9641-5268a8d5f6c0.png)


I think it is a good idea to put CentOS compilation compatibility in CI.

https://github.com/OPM/ResInsight/blob/dev/.github/workflows/centos7.yml

**Comment by mithro** [comment]
BTW Centos 8 was End of Lifed in December 2021 (see https://www.centos.org/centos-linux-eol/) but surprisingly Centos 7 will get maintenance updates until 2024-06-30!

**Comment by msaideroglu** [comment]
Bur my system is Centos 7. Which gcc version should I used? Is the problem that is above because of git or gcc version?

**Comment by msaideroglu** [comment]
I almost use same system properties with the compilation guideline video on youtube:
![Screenshot from 2022-03-05 23-04-13](https://user-images.githubusercontent.com/23635889/156898797-16a2b62d-216a-4096-b071-1e08692a40b9.png)
However it gives errors like this:
![Screenshot from 2022-03-05 23-22-21](https://user-images.githubusercontent.com/23635889/156898845-c66594d8-8fc5-4f71-8c2a-45a9ac8489c9.png)
How can I solve this issue?
