### ISSUE TITLE
some question about simulation

### ISSUE THREAD

**Issue by kangliyu1** [lnis-uofu/OpenFPGA#574]
> **Describe the bug**
Hello, I used the testbench generated by the openfpga platform to simulate after mapping the encryption module of openfpga_flow/benchmarks/iwls2005/aes_core to the FPGA module I generated, and found that the simulation results were wrong (as shown in Figure 1, Figure 2 is vivado The simulation result), many signals will appear unknown state (X state), 

how did you build the testbench of this routine, but the whole process of openfpga did not report an error, so I would like to ask you when you are testing these routines? How to deal with these problems, how to locate the problem of the FPGA module or the problem of test excitation? How to locate the problem?

> **To Reproduce**
Version: 1.1.53-dev+968a03cd-dirty

> **Screenshots**
fig1:
![image](https://user-images.githubusercontent.com/76480905/156603908-289b5947-c525-478e-8f0d-59902c2025a2.png)

fig2:
![image](https://user-images.githubusercontent.com/76480905/156604562-ff007ca8-6d24-4e31-9f08-a4934790309a.png)

> **Enviornment (please complete the following information):**
ubuntu 20.04

**Comment by zliu1Charlotte** [comment]
I port the netlist into vivado and my gfpga outputs are all 'z', do you remember how to resolve this issue?

**Comment by kangliyu1** [comment]
sorry, i didn't fix it




------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"Mike ***@***.***&gt;;
Send time:&nbsp;Wednesday, Sep 21, 2022 1:54 AM
***@***.***&gt;; 
Cc:&nbsp;"さ挚さ挚 ***@***.***&gt;; "State ***@***.***&gt;; 
Subject: &nbsp;Re: [lnis-uofu/OpenFPGA] some question about simulation (Issue #574)





 
I port the netlist into vivado and my gfpga outputs are all 'z', do you remember how to resolve this issue?
