### ISSUE TITLE
Sky130 Openfpga architecture

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#609]
1 - Why Sky130 Openfpga architecture use 45nm.pm technology file as input. In this way are power and timing analysis results reliable?
2- `<circuit_model type="inv_buf" name="sky130_fd_sc_hd__inv_1" prefix="sky130_fd_sc_hd__inv_1" is_default="true">
<design_technology type="cmos" topology="inverter" size="1"/>
<device_technology device_model_name="logic"/>
<port type="input" prefix="in" lib_name="A" size="1"/>
<port type="output" prefix="out" lib_name="Y" size="1"/>
<delay_matrix type="rise" in_port="in" out_port="out"> 10e-12 </delay_matrix>
<delay_matrix type="fall" in_port="in" out_port="out"> 10e-12 </delay_matrix>
</circuit_model>`
What this 10e-12 delay mean? If we want to generate a technology mapped Openfpga with another PDK, how can we determine this delay value? More spesificly, how much capacitance this inverter should be simulated with to determine this value?

**Comment by ganeshgore** [comment]
@msaideroglu  In Sky130 architecture, we did not use VPR/OpenFPGA to measure the power and timing numbers.
The power and timing analysis is performed directly on the Post PnR netlist.

**Comment by msaideroglu** [comment]
Thanks @ganeshgore.
