### ISSUE TITLE
Fabric key doesn't allow to configure fabric layout size

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#688]
Hi. I'm working on FPGA1212_SOFA_CHD_task. When I keep 12x12 layout size, it succesfully generates fabric. However when I give 2x2 as layout size input it gives this type errors: 
````
Finish execution with 2 errors

The entire OpenFPGA flow took 0.101883 seconds

Thank you for using OpenFPGA!

** (process:6308): WARNING **: 16:41:21.172: Duplicate key (MainCanvas) ignored in application::add_canvas.
Error 1: Invalid key alias 'sb_12__12_'!
Error 2: Command 'build_fabric' execution has fatal errors
1
````
When I change `build_fabric --compress_routing --duplicate_grid_pin --load_fabric_key ${EXTERNAL_FABRIC_KEY_FILE}` as `build_fabric --compress_routing --duplicate_grid_pin` then it generates.
What this fabric key does? When I do not use what changes in fabric generation? When I want to change layout size, do I need to change fabric key as well?

I also attached openfpgashell.log file:

[openfpgashell.log](https://github.com/lnis-uofu/OpenFPGA/files/8947252/openfpgashell.log)

**Comment by tangxifan** [comment]
@mattvlsi You can see how fabric key works in the online documentation 

https://openfpga.readthedocs.io/en/master/manual/arch_lang/fabric_key/

A fabric key is binded to a fixed layout, such as ``12x12``. 
If you want a smaller fabric, you need a new fabric key.
Or you can disable the use of  fabric key when calling ``build_fabric``, if you do not need a fabric key.
