### ISSUE TITLE
bb_cost_check error with SOFA

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#694]
When I try to running full_testbench task with a SOFA architecture file, and choose layout size as 2x2, I am getting this type of error on openfpgashell.log:
`Error 1: bb_cost_check: 0.569693 and bb_cost: 0.55274 differ in check_place.`
What is this error about? 
[openfpgashell.log](https://github.com/lnis-uofu/OpenFPGA/files/8999059/openfpgashell.log)

**Comment by tangxifan** [comment]
@msaideroglu The problem should be resolved by merging the PR. Let me know if it works for you.
