### ISSUE TITLE
Failed to find matching architecture model for 'ALU'

### ISSUE THREAD

**Issue by yunuseryilmaz18** [lnis-uofu/OpenFPGA#705]
Hello, I want to benchmark FPGA architectures with a RISC-V processor. I've created blif file of the processor and run VPR with `./vpr k4_frac_N4_tileable_40nm.xml riscv-cpu.blif --disp on` but it gives `Failed to find matching architecture model for 'ALU'` error. How can I run designs with multiple files in VPR?

The blif file:
[riscv-cpu.zip](https://github.com/lnis-uofu/OpenFPGA/files/9045531/riscv-cpu.zip)

**Comment by tangxifan** [comment]
@yunuseryilmaz18 It looks like you have defined a blackbox ``ALU`` in Yosys when synthesis.

![image](https://user-images.githubusercontent.com/11499826/177830730-8053d4ff-ac6f-461f-b4bc-ce85428c1239.png)

Please double check your synthesis scripts. If you are using OpenFPGA's example scripts, you expect to see only LUTs and FFs.

https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/misc/ys_tmpl_yosys_vpr_flow.ys

Currently, VPR supports single BLIF and eBLIF.

**Comment by yunuseryilmaz18** [comment]
I've added -noblackbox argument to read_verilog command and it works now. Thank you.
