### ISSUE TITLE
Support for multiple PCF at a time

### ISSUE THREAD

**Issue by tornupnegatives** [lnis-uofu/OpenFPGA#746]
> **Describe the bug**
It is presently impossible to apply pin constraints to more than one benchmark at a time. Setting the `openfpga_pcf` and `openfpga_vpr_fix_pins` parameters in the configuration file will cause all non-target benchmarks to fail synthesis and place and route.

> A clear and concise description of what the bug is.

[ ] OpenFPGA flow

[ ] VPR

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Clone OpenFPGA repository and checkout commit id: ec31e12
> 2. Add one additional benchmark to the basic_tests/constrain_pin_location task
> 2. Execute OpenFPGA task: basic_tests/constrain_pin_location

> 3. See error
```
Error 1: PCF basic check passed
Error 2: Net 'a' from .pcf is neither defined as input nor output in .blif!
Error 3: Net 'b' from .pcf is neither defined as input nor output in .blif!
Error 4: Net 'c' from .pcf is neither defined as input nor output in .blif!
Error 5:
Type: Placement file
File: /dtools/openfpga/OpenFPGA/vpr/src/base/read_place.cpp
Line: 157
Message: 'and2_fix_pins.place' - Cannot find IO pads location file.
```

> **Expected behavior**
> Specifying per-benchmark PCF files should result in successful execution. Benchmarks which are not associated with a PCF file should use the "default" .place file.

> **Screenshots**
> If applicable, add screenshots to help explain your problem.

> **Enviornment (please complete the following information):**

>  - OS: 

    - [ ] Ubuntu 18.04

>  - Compiler:

> - Version:

> **Additional context**
> Add any other context about the problem here.

**Comment by tangxifan** [comment]
@tornupnegatives Please give a try like:

https://github.com/lnis-uofu/OpenFPGA/blob/2a43843bd7a7e73f2fdfd9563d34cdb3016d4051/openfpga_flow/tasks/quicklogic_tests/flow_test/config/task.conf#L67

For each benchmark, you specify a different parameters. For example, ``bench0_openfpga_pcf``
