### ISSUE TITLE
Question about GPIO selection 

### ISSUE THREAD

**Issue by Baungarten-CINVESTAV** [lnis-uofu/OpenFPGA#764]
Hello

My question is about the selection of the GPIO after my FPGA was made.

 For example, if i have my FPGA and i want to implement an "AND" gate I just need to generate the bitstream with the "AND" gate and then send it to the FPGA to be configured. 

The question is how i can choose the specific port that will be coneted to that "AND" gate and then generate the bitstrean to implemen it in the FPGA.

So far i am using the "device_auto" task  in "fpga_bitstream/generate_bitstream/configuration_chain/device_auto" to generate the bitstream but without I/O pin selection.

-thanks in advance

**Comment by tangxifan** [comment]
@Baungarten-CINVESTAV 

Please check out the following examples:

https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/tasks/basic_tests/constrain_pin_location/config/task.conf

https://github.com/lnis-uofu/OpenFPGA/blob/master/openfpga_flow/tasks/basic_tests/fix_pins/config/task.conf

With documentation:

https://openfpga.readthedocs.io/en/master/manual/openfpga_shell/openfpga_commands/setup_commands/#pcf2place
