### ISSUE TITLE
How to fix the input and output ports of the benchmark to a specific position when using openfpga

### ISSUE THREAD

**Issue by narutozxp** [lnis-uofu/OpenFPGA#765]
In the process of using openfpga before, I don't know how to fix the benchmark port. How to fix the input and output pins of the benchmark in the process of using openfpga?

**Comment by tangxifan** [comment]
@narutozxp Please check the answer: https://github.com/lnis-uofu/OpenFPGA/issues/749#issuecomment-1232159652

**Comment by tangxifan** [comment]
Close the issue as answered. If you need further help, please comment (reopen this issue) or create a new issue.
Thank you for the interests in OpenFPGA.
