### ISSUE TITLE
issue with a nand gate

### ISSUE THREAD

**Issue by omarghoneim3** [lnis-uofu/OpenFPGA#771]
I get this message when I use NAND gate instead of AND GATE
python3 openfpga_flow/scripts/run_fpga_task.py basic_tests/full_testbench/configuration_chain
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task basic_tests/full_testbench/configuration_chain
 INFO (     MainThread) - Created "run025" directory for current task run
 INFO (     MainThread) - Running "yosys_vpr" flow
 INFO (     MainThread) - Found 1 Architectures 3 Benchmarks & 1 Script Parameters
 INFO (     MainThread) - Created total 3 jobs
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Failed to execute openfpga flow - 00_nand2_MIN_ROUTE_CHAN_WIDTH
Traceback (most recent call last):
  File "openfpga_flow/scripts/run_fpga_task.py", line 513, in run_single_script
subprocess.CalledProcessError: Command 'python3 /home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py /home/omar/OpenFPGA/openfpga_flow/vpr_arch/k4_N4_tileable_40nm.xml /home/omar/OpenFPGA/openfpga_flow/benchmarks/micro_benchmark/nand2/nand2.v --top_module nand2 --run_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run025/k4_N4_tileable_40nm/nand2/MIN_ROUTE_CHAN_WIDTH --fpga_flow yosys_vpr --openfpga_shell_template /home/omar/OpenFPGA/openfpga_flow/openfpga_shell_scripts/write_full_testbench_example_script.openfpga --openfpga_arch_file /home/omar/OpenFPGA/openfpga_flow/openfpga_arch/k4_N4_40nm_cc_openfpga.xml --openfpga_sim_setting_file /home/omar/OpenFPGA/openfpga_flow/openfpga_simulation_settings/auto_sim_openfpga.xml --openfpga_vpr_device_layout  --openfpga_fast_configuration  --power --power_tech /home/omar/OpenFPGA/openfpga_flow/tech/PTM_45nm/45nm.xml --vpr_fpga_verilog --vpr_fpga_verilog_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run025/k4_N4_tileable_40nm/nand2/MIN_ROUTE_CHAN_WIDTH --vpr_fpga_x2p_rename_illegal_port --end_flow_with_test --TOP nand2 --CHAN_WIDTH 300 --READ_VERILOG_OPTIONS -nolatches' returned non-zero exit status 0.

**Comment by omarghoneim3** [comment]
NAND2.v
/////////////////////////////////////////
//  Functionality: 2-input NAND 
//  Author:        Xifan Tang
////////////////////////////////////////
`timescale 1ns / 1ps

module Nand2(
  a,
  b,
  c);

input wire a;
input wire b;
output wire c;

assign c = ~ (a & b);

endmodule
NAND_latch
/////////////////////////////////////////
//  Functionality: 2-input AND with clocked 
//                 and combinational outputs 
//  Author:        
////////////////////////////////////////

`timescale 1ns / 1ps

module nand2_latch(
  a,
  b,
  clk,
  c,
  d);

input wire clk;

input wire a;
input wire b;
output wire c;
output reg d;

assign c = ~(a & b);

always @(posedge clk) begin
  d <= c;
end

endmodule

**Comment by tangxifan** [comment]
@omarghoneim3 Can you enable ``--debug --show_thread_logs`` when running the test? It will show detailed error messages.

**Comment by omarghoneim3** [comment]
python3 openfpga_flow/scripts/run_fpga_task.py basic_tests/full_testbench/configuration_chain --show_thread_logs
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task basic_tests/full_testbench/configuration_chain
 INFO (     MainThread) - Created "run030" directory for current task run
 INFO (     MainThread) - Running "yosys_vpr" flow
 INFO (     MainThread) - Found 1 Architectures 3 Benchmarks & 1 Script Parameters
 INFO (     MainThread) - Created total 3 jobs
 INFO (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Validating command line arguments
 INFO (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Run directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run030/k4_N4_tileable_40nm/nand2/MIN_ROUTE_CHAN_WIDTH
 INFO (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Running "yosys_vpr" Flow
 INFO (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Extracted lut_size size from arch XML = 4
 INFO (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Running Yosys with lut_size = 4
 INFO (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Launching Run yosys 
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Run yosys run failed with returncode 1
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - command /home/omar/OpenFPGA/yosys/install/bin/yosys yosys.ys
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - -->>ERROR: Module `nand2' not found!
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Current working directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run030/k4_N4_tileable_40nm/nand2/MIN_ROUTE_CHAN_WIDTH
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Failed to run Run yosys task
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Exiting . . . . . .
 INFO (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Validating command line arguments
 INFO (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Run directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run030/k4_N4_tileable_40nm/xor2/MIN_ROUTE_CHAN_WIDTH
 INFO (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Running "yosys_vpr" Flow
 INFO (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Extracted lut_size size from arch XML = 4
 INFO (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Running Yosys with lut_size = 4
 INFO (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Launching Run yosys 
ERROR (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Run yosys run failed with returncode 1
ERROR (00_xor2_MIN_ROUTE_CHAN_WIDTH) - command /home/omar/OpenFPGA/yosys/install/bin/yosys yosys.ys
ERROR (00_xor2_MIN_ROUTE_CHAN_WIDTH) - -->>ERROR: Module `xor2' not found!
ERROR (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Current working directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run030/k4_N4_tileable_40nm/xor2/MIN_ROUTE_CHAN_WIDTH
ERROR (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Failed to run Run yosys task
ERROR (00_xor2_MIN_ROUTE_CHAN_WIDTH) - Exiting . . . . . .
ERROR (00_nand2_MIN_ROUTE_CHAN_WIDTH) - Failed to execute openfpga flow - 00_nand2_MIN_ROUTE_CHAN_WIDTH
Traceback (most recent call last):
  File "openfpga_flow/scripts/run_fpga_task.py", line 513, in run_single_script
subprocess.CalledProcessError: Command 'python3 /home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py /home/omar/OpenFPGA/openfpga_flow/vpr_arch/k4_N4_tileable_40nm.xml /home/omar/OpenFPGA/openfpga_flow/benchmarks/micro_benchmark/nand2/nand2.v --top_module nand2 --run_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run030/k4_N4_tileable_40nm/nand2/MIN_ROUTE_CHAN_WIDTH --fpga_flow yosys_vpr --openfpga_shell_template /home/omar/OpenFPGA/openfpga_flow/openfpga_shell_scripts/write_full_testbench_example_script.openfpga --openfpga_arch_file /home/omar/OpenFPGA/openfpga_flow/openfpga_arch/k4_N4_40nm_cc_openfpga.xml --openfpga_sim_setting_file /home/omar/OpenFPGA/openfpga_flow/openfpga_simulation_settings/auto_sim_openfpga.xml --openfpga_vpr_device_layout  --openfpga_fast_configuration  --power --power_tech /home/omar/OpenFPGA/openfpga_flow/tech/PTM_45nm/45nm.xml --vpr_fpga_verilog --vpr_fpga_verilog_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run030/k4_N4_tileable_40nm/nand2/MIN_ROUTE_CHAN_WIDTH --vpr_fpga_x2p_rename_illegal_port --end_flow_with_test --TOP nand2 --CHAN_WIDTH 300 --READ_VERILOG_OPTIONS -nolatches' returned non-zero exit status 0.

**Comment by tangxifan** [comment]
@omarghoneim3 The module name in your HDL is ``Nand2`` while in the task configuration file is ``nand2``. Please be aware that the name is case-sensitive.
