### ISSUE TITLE
Build an FPGA fabric using Standard Cell Libraries - simulation error

### ISSUE THREAD

**Issue by zliu1Charlotte** [lnis-uofu/OpenFPGA#773]
Hi, 

I am doing a walk-through on Build an FPGA fabric using Standard Cell Libraries from OpenFPGA Documentation, Release 1.1.457.

I am not able to get what Fig. 5.2: Simulation Waveforms with OpenFPGA Circuit Model is showing. 

My vcd file only gives up to 1892ps (in Fig. 5.2 we can see simulation up to 30ns). Is there a way to fix this? Thanks.

**Comment by tangxifan** [comment]
@zliu1Charlotte Can you provide the link to the documentation? 
You can customize the simulation period by using the XML syntax in simulation setting files:

https://openfpga.readthedocs.io/en/master/manual/arch_lang/simulation_setting/#operating-clock-setting
