### ISSUE TITLE
problem with modelsim! The model sim project is not created

### ISSUE THREAD

**Issue by omarghoneim3** [lnis-uofu/OpenFPGA#779]
python3 openfpga_flow/scripts/run_modelsim.py basic_tests/full_testbench/configuration_chain --run_sim
INFO (MainThread) - Created log file at /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/latest/modelsim_run.log
INFO (MainThread) - Found 0 INI files
INFO (MainThread) - Launching 2 parallel threads
INFO (MainThread) - = = = == = = == = = == = = == = = == = = == = = == = = == = = == = = =
INFO (MainThread) - Passed Jobs 0/0
INFO (MainThread) - Result file stored at /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/latest/modelsim_result.csv
INFO (MainThread) - = = = == = = == = = == = = == = = == = = == = = == = = == = = == = = =

**Comment by tangxifan** [comment]
@omarghoneim3 Run sim is not maintained these days due to the lack of modelsim licenses. Please create the MSIM project yourself.
