### ISSUE TITLE
Whether openfpga has modified the original VPR？

### ISSUE THREAD

**Issue by narutozxp** [lnis-uofu/OpenFPGA#782]
When I use the VPR in a separate VTR for placement and routing (vpr /home/data/shawn/eFPGA/Code/OpenFPGA/OpenFPGA-1.1.0/openfpga_flow/tasks/basic_tests/narutozxp/work/run021/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm/FSM_top /MIN_ROUTE_CHAN_WIDTH/arch/k6_frac_N10_tileable_adder_chain_dpram8K_dsp36_fracff_40nm.xml FSM_top.blif --device 12x12clb --constant_net_method route), it will report that "tileable" cannot be recognized. But if i use the VPR command from the openfpga suite, this problem doesn't occur

**Comment by tangxifan** [comment]
@narutozxp Please checkout the documentation:

https://openfpga.readthedocs.io/en/master/manual/arch_lang/addon_vpr_syntax/

**Comment by tangxifan** [comment]
We are contributing OpenFPGA's technical features to VTR upstream these days. See details in https://github.com/lnis-uofu/OpenFPGA/pull/747
