### ISSUE TITLE
Differences in two openfpga_arch

### ISSUE THREAD

**Issue by zliu1Charlotte** [lnis-uofu/OpenFPGA#789]
Hi, I have a short question,
What is the differences between:
k4_frac_N8_reset_softadder_register_scan_chain_frac_dsp16_caravel_io_skywater130nm_fdhd_cc_openfpga.xml
and
k4_frac_N8_reset_softadderSuperLUT_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml
Why in the openfpga_flow/tasks/quicklogic_tests/lut_adder_test/config/task.conf
We choose k4_frac_N8_reset_softadderSuperLUT_register_scan_chain_caravel_io_skywater130nm_fdhd_cc_openfpga.xml

**Comment by tangxifan** [comment]
@zliu1Charlotte It is because the soft adder implementation in the ``softadder.xml`` is not well supported by QuickLogic's synthesis engine,  while the ``softadderSuperLUT`` is.
