### ISSUE TITLE
Yosys does not techmap appropriate fracturable DSP mode

### ISSUE THREAD

**Issue by mustafaarslan0** [lnis-uofu/OpenFPGA#813]
> Yosys does not techmap appropriate fracturable DSP mode
> I work on FPGA arch which has fracturable mult32 hard block (k4_frac_N4_tileable_adder_chain_mem1K_frac_dsp32_40nm).
>Yosys always maps all multiplications to given DSP name that written in the config file.

>Which part of OpenFPGA is buggy 
 > Yosys 

> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Clone OpenFPGA repository and checkout commit id: 8ee3fb8 (v1.2.0)
> 2. Execute OpenFPGA task ~/OpenFPGA/openfpga_flow/tasks/fpga_verilog/dsp/multi_mode_mult_16x16
> 3. See .blif files of all benchmarks.
> 4. Change the DSP parameters in the .conf file for mult_16x16. 
> 5. Execute task again. See .blif files of all benchmarks.

> **Expected behavior**
> Techmap to appropriate DSP mode.

**Comment by tangxifan** [comment]
@mustafaarslan0 I am aware of this issue. Currently, I do not have a better solution. You may have to ask Yosys community and see if there is any solution.
