### ISSUE TITLE
Repack fails on fracturable dsp36 architecture

### ISSUE THREAD

**Issue by mustafaarslan0** [lnis-uofu/OpenFPGA#815]
OpenFPGA shell fails when running task with fracturable dsp36 architecture.
Shell gives me this error:
![image](https://user-images.githubusercontent.com/24413057/192759767-2215facb-dd90-4a69-873a-6afd59281bff.png)

Task:
[task_frac_dsp36.zip](https://github.com/lnis-uofu/OpenFPGA/files/9664457/task_frac_dsp36.zip)

**Comment by mustafaarslan0** [comment]
Thank you for review. I think we need appropriate DSP techmap files and YoSYS script to map all DSP modes. Issue #813

**Comment by tangxifan** [comment]
@mustafaarslan0 I see you patches. I believe the issue has been resolved. Close this issue now. If you see problem insists, please reopen.
