### ISSUE TITLE
ace2 related question

### ISSUE THREAD

**Issue by zliu1Charlotte** [lnis-uofu/OpenFPGA#863]
Hi, I run into a question about ace2. 
I know that we are able to bypass the ace2 in the openfpga shell script. 
Currently I am not sure where the ace2 is being used in openfpga (in my case)? 
What I need on my end is to have the fabric netlist and bitstream, I use commercial tools to do simulation and power generation. So I wonder if I skip this ace2 step would it effect my lateral simulation and power analysis which I won't be using this .act file anyways. Thank you.

**Comment by tangxifan** [comment]
No impact on your later simulation. It is just analysis
