### ISSUE TITLE
A bigger design is routable but sub-block of that design is not routable seperately

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#883]
I'm running a uart benchmark on a k4n8 architecture file with no local routing. It's adapted from a sky130 architecture. Although I can run several benchmarks on it, I am facing some interesting cases. A **uart** top module and **uart_tx** submodule seperately can be placed and routed. However when I try to run **uart_rx** sub-module seperately it says "**Circuit is unroutable with a channel width factor of 60.**" . Also when I run vpr command in task directory to see what minimum route-channel is, it says **"Message: This circuit requires a channel width above 1000, probably is not going to route.
Aborting routing procedure."**

A bigger design is routable but sub-block of that design is not routable seperately. How can I solve this issue @tangxifan?

openfpgashell.log for uart_rx task is:
[openfpgashell.log](https://github.com/lnis-uofu/OpenFPGA/files/9958600/openfpgashell.log)

**Comment by tangxifan** [comment]
I see this issue in recent VTR upgrade. Currently, I do not have a better solution than trying different routing channel width numbers.
