### ISSUE TITLE
how to using custom mux in openfpga

### ISSUE THREAD

**Issue by narutozxp** [lnis-uofu/OpenFPGA#890]
Whether a Multiplexer can be built with a four-input mux（or larger）.Because I read in your paper that you customized a lot of mux（1-level N -input multiplexers (2 ≤N ≤ 7)），So I also want to customize the unit to improve the performance。Is there an appropriate demo to tell openfpga how to use these custom units.
thanks a lot!

**Comment by tangxifan** [comment]
You may look into the ``mux_primitives.v`` file. For each module inside, you may consider to customize them.
