### ISSUE TITLE
I am getting this error, but I am not sure where it comes from

### ISSUE THREAD

**Issue by omarghoneim3** [lnis-uofu/OpenFPGA#904]
python3 openfpga_flow/scripts/run_fpga_task.py basic_tests/full_testbench/configuration_chain --show_thread_logs
 INFO (     MainThread) - Set up to run 2 Parallel threads
 INFO (     MainThread) - Currently running task basic_tests/full_testbench/configuration_chain
 INFO (     MainThread) - Created "run167" directory for current task run
 INFO (     MainThread) - Running "yosys_vpr" flow
 INFO (     MainThread) - Found 1 Architectures 3 Benchmarks & 1 Script Parameters
 INFO (     MainThread) - Created total 3 jobs
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Validating command line arguments
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Run directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run167/k4_N4_OpenFPGA_simulation/24clock.v/MIN_ROUTE_CHAN_WIDTH
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Running "yosys_vpr" Flow
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Extracted lut_size size from arch XML = 4
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Running Yosys with lut_size = 4
 INFO (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Launching Run yosys 
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - Validating command line arguments
 INFO (00_or2_MIN_ROUTE_CHAN_WIDTH) - Run directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run167/k4_N4_OpenFPGA_simulation/or2/MIN_ROUTE_CHAN_WIDTH
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Run yosys run failed with returncode 1
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - command /home/omar/OpenFPGA/yosys/install/bin/yosys yosys.ys
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - -->>./benchmark/24clock.v:1: ERROR: syntax error, unexpected TOK_CONSTVAL, expecting TOK_ID
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Current working directory : /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run167/k4_N4_OpenFPGA_simulation/24clock.v/MIN_ROUTE_CHAN_WIDTH
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Failed to run Run yosys task
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Exiting . . . . . .
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - Failed to execute openfpga flow - 00_24clock.v_MIN_ROUTE_CHAN_WIDTH
Traceback (most recent call last):
  File "openfpga_flow/scripts/run_fpga_task.py", line 513, in run_single_script
subprocess.CalledProcessError: Command 'python3 /home/omar/OpenFPGA/openfpga_flow/scripts/run_fpga_flow.py /home/omar/OpenFPGA/openfpga_flow/vpr_arch/k4_N4_OpenFPGA_simulation.xml /home/omar/OpenFPGA/openfpga_flow/benchmarks/micro_benchmark/24clock/24clock.v --top_module 24clock.v --run_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run167/k4_N4_OpenFPGA_simulation/24clock.v/MIN_ROUTE_CHAN_WIDTH --fpga_flow yosys_vpr --openfpga_shell_template /home/omar/OpenFPGA/openfpga_flow/openfpga_shell_scripts/write_full_testbench_example_script.openfpga --openfpga_arch_file /home/omar/OpenFPGA/openfpga_flow/openfpga_arch/k4_N4_openfpga_arch.xml --openfpga_sim_setting_file /home/omar/OpenFPGA/openfpga_flow/openfpga_simulation_settings/auto_sim_openfpga.xml --openfpga_vpr_device_layout  --openfpga_fast_configuration  --power --power_tech /home/omar/OpenFPGA/openfpga_flow/tech/PTM_45nm/45nm.xml --vpr_fpga_verilog --vpr_fpga_verilog_dir /home/omar/OpenFPGA/openfpga_flow/tasks/basic_tests/full_testbench/configuration_chain/run167/k4_N4_OpenFPGA_simulation/24clock.v/MIN_ROUTE_CHAN_WIDTH --vpr_fpga_x2p_rename_illegal_port --end_flow_with_test --TOP 24clock.v --CHAN_WIDTH 300 --READ_VERILOG_OPTIONS -nolatches' returned non-zero exit status 0.

**Comment by tangxifan** [comment]
@omarghoneim3 Please check your yosys log files, as the error comes from yosys:

```
ERROR (00_24clock.v_MIN_ROUTE_CHAN_WIDTH) - -->>./benchmark/24clock.v:1: ERROR: syntax error, unexpected TOK_CONSTVAL, expecting TOK_ID
```
