### ISSUE TITLE
Hard IP Integration with OpenFPGA

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#929]
Is it possible to add any hard-IP to be automatically elaborated by Yosys such as FIFO, UART in FPGA as sub-tiles. I want to have embedded FIFO and UART blocks that  can be used in the designs with higher performances. If possible, how can I generate technology map files for Yosys?

**Comment by tangxifan** [comment]
@msaideroglu Technology map files for yosys are hand crafted. You can read Yosys manual.
