### ISSUE TITLE
generate area-optimized tiling

### ISSUE THREAD

**Issue by msaideroglu** [lnis-uofu/OpenFPGA#939]
How can I generate area-optimized tiling structures instead of classical tilings as mentioned in the previous presentation below?
![1670243859788](https://user-images.githubusercontent.com/107807649/206100831-1f46f1e1-2d9e-4b01-bd56-40f92ed77d38.jpeg)

**Comment by tangxifan** [comment]
@msaideroglu The tiling strategies are used by physical designers when reshaping the netlists. We are still experimenting the methodologies outside OpenFPGA. We will consider to open-source it next year.

**Comment by msaideroglu** [comment]
Thanks.
