### ISSUE TITLE
Reading .route file

### ISSUE THREAD

**Issue by zliu1Charlotte** [lnis-uofu/OpenFPGA#944]
Hi, I am having issue reading the .route file. 
Cannot upload the .route file here so I will guide as follow:
 
```
Routing:
Net 0 (a[0])
Node:   478     SOURCE (1,4)  Pad: 3  Switch: 0
Node:   494       OPIN (1,4)  Pad: 3  Switch: 2
Node:   665      CHANX (1,3) to (3,3)  Track: (2,4,6)  Switch: 1
Node:   394       IPIN (1,3)  Pin: 8   clb.I[8] Switch: 0
Node:   386       SINK (1,3)  Class: 0  Switch: -1
```

This a[0] is a input net, from SOURCE (1,4) to SINK (1,3).
I understand the OPIN and IPIN.
I wonder why it has to go through `Node:   665      CHANX (1,3) to (3,3)  Track: (2,4,6)  Switch: 1` , instead aren't `CHANX(1,3)` itself should be enough? 
What was the reason it has `Node:   665      CHANX (1,3) to (3,3)  Track: (2,4,6)  Switch: 1`

Because some examples are like:
```
Net 1 (b[0])
Node:   353     SOURCE (0,3)  Pad: 7  Switch: 0
Node:   369       OPIN (0,3)  Pad: 7  Switch: 2
Node:   717      CHANY (0,3)  Track: 0  Switch: 1
Node:   401       IPIN (1,3)  Pin: 3   clb.I[3] Switch: 0
Node:   386       SINK (1,3)  Class: 0  Switch: -1
```
In this case b[0] goes from SOURCE (0,3)  -> CHANY (0,3) -> SINK (1,3). I understand this very quickly. 

Do we have an explanation on this? 

Or `Node:   665      CHANX (1,3) to (3,3)  Track: (2,4,6)  Switch: 1` does not necessary means it will go through all the tracks?

If so, the explanation here gets a bit confusing saying `Instead, a list of the blocks (name and internal index) which this net must connect is printed out. The location of each block and the class of the pin to which the net must connect at each block is also printed.` from https://docs.verilogtorouting.org/en/latest/vpr/file_formats/#vpr-route-file under `Routing File Format Examples`, the paragraph is between `Listing 10 Example routing for a non-global net` and `Listing 11 Example routing for a global net.`

Thanks!

**Comment by zliu1Charlotte** [comment]
This is the routing for clk, if I am not mistaken, I assume the clk will go from SOURCE to the first SINK, and from the first SINK, continue its route then go to the second SINK? 
```
Net 4 (clk)
Node:   191     SOURCE (4,1)  Pad: 1  Switch: 0
Node:   207       OPIN (4,1)  Pad: 1  Switch: 2
Node:   784      CHANY (3,1)  Track: 1  Switch: 2
Node:   578      CHANX (1,0) to (3,0)  Track: (5,3,1)  Switch: 1
Node:   146       IPIN (1,1)  Pin: 14   clb.clk[0] Switch: 0
Node:   133       SINK (1,1)  Class: 5  Switch: -1
Node:   578      CHANX (1,0) to (3,0)  Track: (5,3,1)  Switch: 1
Node:   167       IPIN (2,1)  Pin: 14   clb.clk[0] Switch: 0
Node:   154       SINK (2,1)  Class: 5  Switch: -1
Node:   578      CHANX (1,0) to (3,0)  Track: (5,3,1)  Switch: 2
Node:   695      CHANY (0,1) to (0,3)  Track: (2,4,6)  Switch: 2
Node:   643      CHANX (1,2) to (3,2)  Track: (10,12,14)  Switch: 1
Node:   421       IPIN (2,3)  Pin: 14   clb.clk[0] Switch: 0
Node:   408       SINK (2,3)  Class: 5  Switch: -1
Node:   695      CHANY (0,1) to (0,3)  Track: (2,4,6)  Switch: 2
Node:   671      CHANX (1,3) to (3,3)  Track: (8,10,12)  Switch: 2
Node:   798      CHANY (3,1) to (3,3)  Track: (15,13,11)  Switch: 2
Node:   794      CHANY (3,1) to (3,2)  Track: (11,9)  Switch: 2
Node:   624      CHANX (2,1) to (3,1)  Track: (15,13)  Switch: 1
Node:   315       IPIN (3,2)  Pin: 14   clb.clk[0] Switch: 0
Node:   302       SINK (3,2)  Class: 5  Switch: -1
Node:   798      CHANY (3,1) to (3,3)  Track: (15,13,11)  Switch: 2
Node:   592      CHANX (2,0) to (3,0)  Track: (7,5)  Switch: 1
Node:   188       IPIN (3,1)  Pin: 14   clb.clk[0] Switch: 0
Node:   175       SINK (3,1)  Class: 5  Switch: -1
Node:   671      CHANX (1,3) to (3,3)  Track: (8,10,12)  Switch: 2
Node:   778      CHANY (2,3)  Track: 7  Switch: 2
Node:   636      CHANX (1,2) to (2,2)  Track: (3,1)  Switch: 2
Node:   696      CHANY (0,1) to (0,2)  Track: (3,1)  Switch: 2
Node:   605      CHANX (1,1) to (3,1)  Track: (2,4,6)  Switch: 1
Node:   273       IPIN (1,2)  Pin: 14   clb.clk[0] Switch: 0
Node:   260       SINK (1,2)  Class: 5  Switch: -1
Node:   605      CHANX (1,1) to (3,1)  Track: (2,4,6)  Switch: 1
Node:   294       IPIN (2,2)  Pin: 14   clb.clk[0] Switch: 0
Node:   281       SINK (2,2)  Class: 5  Switch: -1
Node:   636      CHANX (1,2) to (2,2)  Track: (3,1)  Switch: 1
Node:   400       IPIN (1,3)  Pin: 14   clb.clk[0] Switch: 0
Node:   387       SINK (1,3)  Class: 5  Switch: -1
```

**Comment by zliu1Charlotte** [comment]
Another question:
I noticed that we have packer options in the log file:
```
PackerOpts.allow_unrelated_clustering: auto
PackerOpts.alpha_clustering: 0.750000
PackerOpts.beta_clustering: 0.900000
PackerOpts.cluster_seed_type: BLEND2

```
I wish to add this `--write_block_usage` as one of the packer options as well, I wonder where to add this? Thanks

**Comment by tangxifan** [comment]
@zliu1Charlotte You just need to add it to the line where you call vpr. For example:

https://github.com/lnis-uofu/OpenFPGA/blob/014107e78854fb18fb05a27a07dabb8b29d82536/openfpga_flow/openfpga_shell_scripts/example_script.openfpga#L3

**Comment by tangxifan** [comment]
@zliu1Charlotte 

```
Node:   665      CHANX (1,3) to (3,3)  Track: (2,4,6)
```

This is because that in tilable routing architecture, a routing track may have multiple track id.
Tileable routing architecture in OpenFPGA follows staggered wiring. You may find more details in https://ieeexplore.ieee.org/abstract/document/8977869

**Comment by zliu1Charlotte** [comment]
> @zliu1Charlotte You just need to add it to the line where you call vpr. For example:
> 
> https://github.com/lnis-uofu/OpenFPGA/blob/014107e78854fb18fb05a27a07dabb8b29d82536/openfpga_flow/openfpga_shell_scripts/example_script.openfpga#L3

I did `vpr ${VPR_ARCH_FILE} ${VPR_TESTBENCH_BLIF} --clock_modeling route --full_stats on --write_rr_graph example_rr_graph.xml --write_block_usage blocks_usage.txt`
But in the log file it shows error:` Unexpected command-line argument '--write_block_usage'`

**Comment by zliu1Charlotte** [comment]
Hi, I have another question, I see in the openfpga_arch files, for example, `k4_N4_40nm_cc_openfpga.xml`,  what does this 40nm means? 40 nm technology? If I am using skywater 130nm cells, would it be a problem? Thanks.

**Comment by tangxifan** [comment]
@zliu1Charlotte Please refer to the README about naming convention of the architecture files

https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/vpr_arch#readme
https://github.com/lnis-uofu/OpenFPGA/tree/master/openfpga_flow/openfpga_arch#readme

We suggest users to follow the naming convention rules when creating their own architecture files, which is easier for them to identify architecture highlights.
