### ISSUE TITLE
save place and route figure

### ISSUE THREAD

**Issue by zliu1Charlotte** [lnis-uofu/OpenFPGA#956]
Hi, I tried this but I could not find the vpr_placement.pdf and vpr_routing.pdf. 
`vpr ${VPR_ARCH_FILE} ${VPR_TESTBENCH_BLIF} --save_graphics on --disp on --clock_modeling route`
Thanks.

**Comment by tangxifan** [comment]
@zliu1Charlotte Are you trying it in OpenFPGA shell or outside? Currently GUI is not working when calling VPR in openfpga shell.
