### ISSUE TITLE
What is the importance of Yosys rewrite run?

### ISSUE THREAD

**Issue by mustafaarslan0** [lnis-uofu/OpenFPGA#958]
Hi. I try to map some cells to my library cells. But Yosys rewrite run fails OpenFPGA flow because library file is not specified in Yosys rewrite script. What is the importance of Yosys rewrite run? Do I lose any functionality if I remove it?

Thanks.

**Comment by tangxifan** [comment]
@mustafaarslan0 If you prefer to run design verification through OpenFPGA flow, you may need it. Otherwise, you can skip it. It does not impact the bitstream generation results.
